language: java
cache: apt
env:
  global:
    - CI=true
  matrix:
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-git-snapshot-travis

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c9319db5f5a0b70ed2a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install "$EVM_EMACS" --use --skip
install:
  - cask install
  - cask update
#  - cd /tmp
#  - mkdir /home/travis/opt && wget http://download.eclipse.org/technology/epp/downloads/release/luna/R/eclipse-java-luna-R-linux-gtk-x86_64.tar.gz -O eclipse.tar.gz && tar -xf eclipse.tar.gz -C /home/travis/opt
#  - wget http://sourceforge.net/projects/eclim/files/latest/download -O eclim.jar && java -Dvim.skip=true -Declipse.home=/home/travis/opt/eclipse -jar eclim.jar install
#  - cd - && cd test && git clone https://github.com/nschum/elisp-lint.git
#  - cd -
script:
  - make compile
  - make lint
  - make specs test

branches:
  only:
  - master
  - development
